const products = [
    {
        _id : '1',
        name : 'Airpods Wireless Bluetooth Headphones',
        image : '/images/airpods.jpg',
        description: 'Bluetooth Technology',
        brand : 'Apple',
        category : 'Electronics',
        price : 99.9,
        countInstock : 3,
        rating : 4.5,
        numReviews : 4,
    },
    {
        _id : '2',
        name : 'Airpods Wireless Bluetooth Headphones',
        image : '/images/alexa.jpg',
        description: 'Bluetooth Technology',
        brand : 'Apple',
        category : 'Electronics',
        price : 99.9,
        countInstock : 3,
        rating : 4.5,
        numReviews : 4,
    },
    {
        _id : '3',
        name : 'Airpods Wireless Bluetooth Headphones',
        image : '/images/camera.jpg',
        description: 'Bluetooth Technology',
        brand : 'Apple',
        category : 'Electronics',
        price : 99.9,
        countInstock : 3,
        rating : 4.5,
        numReviews : 4,
    },
]

export default products